/**
 * src/api/userAnimeList.ts
 *
 * API functions for managing user anime lists.
 */
import supabase from "../../supabase-client";
import type { UserAnimeEntry, AnimeStatus } from "../../types/database.types";

// #region Helper Functions

/**
 * Create a status_update entry in the feed
 *
 * @param userId uuid of the user
 * @param animeId uuid of the anime
 * @param status new status of the anime
 */
const createStatusUpdateEntry = async (
  userId: string,
  animeId: string,
  status: AnimeStatus
): Promise<void> => {
  const { error } = await supabase.from("entries").insert({
    user_id: userId,
    anime_id: animeId,
    entry_type: "status_update",
    status_value: status,
    content: null,
  });

  if (error) {
    console.error("Error creating status update entry:", error);
    throw error;
  }
};

/**
 * Delete all auto-generated entries for a user's anime
 *
 * @param userId uuid of the user
 * @param animeId uuid of the anime
 */
const deleteAutoGeneratedEntries = async (
  userId: string,
  animeId: string
): Promise<void> => {
  const { error } = await supabase
    .from("entries")
    .delete()
    .eq("user_id", userId)
    .eq("anime_id", animeId)
    .in("entry_type", ["rating", "status_update"]);

  if (error) {
    console.error("Error deleting auto-generated entries:", error);
    throw error;
  }
};

// #endregion Helper Functions

/**
 * Fetch every anime entry for a user (no pagination). Used by the profile
 * page, which groups entries into franchises client-side and therefore needs
 * the complete list.
 *
 * @param userId uuid of the user
 * @returns all of the user's UserAnimeEntry rows with anime joined
 */
export const fetchAllUserAnimeEntries = async (
  userId: string
): Promise<UserAnimeEntry[]> => {
  const { data, error } = await supabase
    .from("user_anime_entries")
    .select("*, anime(*)")
    .eq("user_id", userId)
    .order("updated_at", { ascending: false });

  if (error) throw new Error(error.message);

  return (data ?? []) as UserAnimeEntry[];
};

/**
 * Count a user's completed entries among a set of anime ids. Used for the
 * "N / M seasons completed" franchise hint, which only needs a count over a
 * handful of franchise members rather than the user's full watch history.
 *
 * @param userId uuid of the user
 * @param animeIds anime ids to check (e.g. a franchise's members)
 * @returns number of matching entries with status "completed"
 */
export const countCompletedAnimeEntries = async (
  userId: string,
  animeIds: string[]
): Promise<number> => {
  if (animeIds.length === 0) return 0;

  const { count, error } = await supabase
    .from("user_anime_entries")
    .select("id", { count: "exact", head: true })
    .eq("user_id", userId)
    .eq("status", "completed")
    .in("anime_id", animeIds);

  if (error) throw new Error(error.message);

  return count ?? 0;
};

/**
 * Batch-fetch a user's status for a set of anime ids. Used for the per-season
 * watch-status badges on the sidebar's seasons list, which needs every
 * franchise member's status at once rather than one entry at a time.
 *
 * @param userId uuid of the user
 * @param animeIds anime ids to check (e.g. a franchise's members)
 * @returns a map of anime id to that anime's status, omitting untracked ids
 */
export const fetchUserAnimeStatuses = async (
  userId: string,
  animeIds: string[]
): Promise<Record<string, AnimeStatus>> => {
  if (animeIds.length === 0) return {};

  const { data, error } = await supabase
    .from("user_anime_entries")
    .select("anime_id, status")
    .eq("user_id", userId)
    .in("anime_id", animeIds);

  if (error) throw new Error(error.message);

  return Object.fromEntries(
    (data ?? []).map((entry) => [entry.anime_id, entry.status as AnimeStatus])
  );
};

/**
 * Get a user's anime entry if it exists
 *
 * @param animeId uuid of the anime
 * @param userId uuid of the user
 * @returns a promise that resolves to the UserAnimeEntry if found, or null otherwise
 */
export const getUserAnimeEntry = async (
  animeId: string,
  userId: string
): Promise<UserAnimeEntry | null> => {
  const { data, error } = await supabase
    .from("user_anime_entries")
    .select("*, anime(*)")
    .eq("anime_id", animeId)
    .eq("user_id", userId)
    .maybeSingle();

  if (error) throw new Error(error.message);

  return data as UserAnimeEntry | null;
};

/**
 * Add an anime to the user's list without posting to the feed.
 *
 * The list-state half of `addUserAnimeEntry`. Surfaces that are not
 * publishing an entry — the profile page, the Create composer, which posts
 * its own combined entry — go through this instead.
 *
 * @param animeId uuid of the anime
 * @param userId uuid of the user
 * @param status status of the anime in the user's list (default: "not_started")
 * @returns the newly created UserAnimeEntry
 */
export const addUserAnimeEntryListOnly = async (
  animeId: string,
  userId: string,
  status: AnimeStatus = "not_started"
): Promise<UserAnimeEntry> => {
  const { data, error } = await supabase
    .from("user_anime_entries")
    .insert({
      anime_id: animeId,
      user_id: userId,
      status: status,
    })
    .select("*, anime(*)")
    .single();

  if (error) throw new Error(error.message);

  return data as UserAnimeEntry;
};

/**
 * Add an anime to the user's list and announce it in the feed. Used by the
 * detail-page list button, where adding a show is itself the statement.
 *
 * @param animeId uuid of the anime
 * @param userId uuid of the user
 * @param status status of the anime in the user's list (default: "not_started")
 * @returns the newly created UserAnimeEntry
 */
export const addUserAnimeEntry = async (
  animeId: string,
  userId: string,
  status: AnimeStatus = "not_started"
): Promise<UserAnimeEntry> => {
  const entry = await addUserAnimeEntryListOnly(animeId, userId, status);

  // Create status_update entry in feed
  await createStatusUpdateEntry(userId, animeId, status);

  return entry;
};

/**
 * Update a user anime entry's fields without posting to the feed.
 *
 * The list-state half of `updateUserAnimeEntry`. Editing from the profile
 * goes through this: it is a correction to your own list, not a statement
 * worth broadcasting, and /entry/:id already renders the author's live
 * status and rating rather than the frozen post values.
 *
 * @param entryId uuid of the user anime entry
 * @param updates partial updates to apply (status, rating, or review)
 * @returns the updated UserAnimeEntry
 */
export const updateUserAnimeEntryFields = async (
  entryId: string,
  updates: Partial<Pick<UserAnimeEntry, "status" | "rating" | "review">>
): Promise<UserAnimeEntry> => {
  // updated_at is maintained by the update_user_anime_entries_updated_at
  // trigger, unlike user_franchise_entries which has none and stamps by hand.
  const { data, error } = await supabase
    .from("user_anime_entries")
    .update(updates)
    .eq("id", entryId)
    .select("*, anime(*)")
    .single();

  if (error) throw new Error(error.message);

  return data as UserAnimeEntry;
};

/**
 * Update an existing user anime entry, posting a status_update to the feed
 * when the status actually changed.
 *
 * @param entryId uuid of the user anime entry
 * @param updates partial updates to apply (status, rating, or review)
 * @returns the updated UserAnimeEntry
 */
export const updateUserAnimeEntry = async (
  entryId: string,
  updates: Partial<Pick<UserAnimeEntry, "status" | "rating" | "review">>
): Promise<UserAnimeEntry> => {
  // First, fetch the current entry to compare values
  const { data: currentEntry, error: fetchError } = await supabase
    .from("user_anime_entries")
    .select("user_id, anime_id, status, rating")
    .eq("id", entryId)
    .single();
  if (fetchError) throw new Error(fetchError.message);

  const data = await updateUserAnimeEntryFields(entryId, updates);

  // Status changes still post feed events; rating changes don't create
  // posts — the entry page displays the author's current rating live
  const changedStatus =
    updates.status && updates.status !== currentEntry.status;

  if (changedStatus) {
    await createStatusUpdateEntry(
      currentEntry.user_id,
      currentEntry.anime_id,
      updates.status!
    );
  }

  return data;
};

/**
 * Remove an anime from the user's list
 *
 * @param entryId uuid of the user anime entry to remove
 */
export const removeUserAnimeEntry = async (entryId: string): Promise<void> => {
  // First, get the entry details to delete associated entries
  const { data: entry, error: fetchError } = await supabase
    .from("user_anime_entries")
    .select("user_id, anime_id")
    .eq("id", entryId)
    .single();
  if (fetchError) throw new Error(fetchError.message);

  // Independent tables — run together rather than one after the other.
  const [, { error }] = await Promise.all([
    deleteAutoGeneratedEntries(entry.user_id, entry.anime_id),
    supabase.from("user_anime_entries").delete().eq("id", entryId),
  ]);

  if (error) throw new Error(error.message);
};
