/**
 * src/api/userAnimeList.ts
 *
 * API functions for managing user anime lists.
 */
import supabase from "../../supabase-client";
import type { UserAnimeEntry, AnimeStatus } from "../../types/database.types";

// #region Helper Functions

/**
 * Create a status_update entry in the feed
 *
 * @param userId uuid of the user
 * @param animeId uuid of the anime
 * @param status new status of the anime
 */
const createStatusUpdateEntry = async (
  userId: string,
  animeId: string,
  status: AnimeStatus
): Promise<void> => {
  const { error } = await supabase.from("entries").insert({
    user_id: userId,
    anime_id: animeId,
    entry_type: "status_update",
    status_value: status,
    content: null,
  });

  if (error) {
    console.error("Error creating status update entry:", error);
    throw error;
  }
};

/**
 * Delete all auto-generated entries for a user's anime
 *
 * @param userId uuid of the user
 * @param animeId uuid of the anime
 */
const deleteAutoGeneratedEntries = async (
  userId: string,
  animeId: string
): Promise<void> => {
  const { error } = await supabase
    .from("entries")
    .delete()
    .eq("user_id", userId)
    .eq("anime_id", animeId)
    .in("entry_type", ["rating", "status_update"]);

  if (error) {
    console.error("Error deleting auto-generated entries:", error);
    throw error;
  }
};

// #endregion Helper Functions

/**
 * Fetch every anime entry for a user (no pagination). Used by the profile
 * page, which groups entries into franchises client-side and therefore needs
 * the complete list.
 *
 * @param userId uuid of the user
 * @returns all of the user's UserAnimeEntry rows with anime joined
 */
export const fetchAllUserAnimeEntries = async (
  userId: string
): Promise<UserAnimeEntry[]> => {
  const { data, error } = await supabase
    .from("user_anime_entries")
    .select("*, anime(*)")
    .eq("user_id", userId)
    .order("updated_at", { ascending: false });

  if (error) throw new Error(error.message);

  return (data ?? []) as UserAnimeEntry[];
};

/**
 * Count a user's completed entries among a set of anime ids. Used for the
 * "N / M seasons completed" franchise hint, which only needs a count over a
 * handful of franchise members rather than the user's full watch history.
 *
 * @param userId uuid of the user
 * @param animeIds anime ids to check (e.g. a franchise's members)
 * @returns number of matching entries with status "completed"
 */
export const countCompletedAnimeEntries = async (
  userId: string,
  animeIds: string[]
): Promise<number> => {
  if (animeIds.length === 0) return 0;

  const { count, error } = await supabase
    .from("user_anime_entries")
    .select("id", { count: "exact", head: true })
    .eq("user_id", userId)
    .eq("status", "completed")
    .in("anime_id", animeIds);

  if (error) throw new Error(error.message);

  return count ?? 0;
};

/**
 * Get a user's anime entry if it exists
 *
 * @param animeId uuid of the anime
 * @param userId uuid of the user
 * @returns a promise that resolves to the UserAnimeEntry if found, or null otherwise
 */
export const getUserAnimeEntry = async (
  animeId: string,
  userId: string
): Promise<UserAnimeEntry | null> => {
  const { data, error } = await supabase
    .from("user_anime_entries")
    .select("*, anime(*)")
    .eq("anime_id", animeId)
    .eq("user_id", userId)
    .maybeSingle();

  if (error) throw new Error(error.message);

  return data as UserAnimeEntry | null;
};

/**
 * Add an anime to the user's list
 *
 * @param animeId uuid of the anime
 * @param userId uuid of the user
 * @param status status of the anime in the user's list (default: "not_started")
 * @returns the newly created UserAnimeEntry
 */
export const addUserAnimeEntry = async (
  animeId: string,
  userId: string,
  status: AnimeStatus = "not_started"
): Promise<UserAnimeEntry> => {
  const { data, error } = await supabase
    .from("user_anime_entries")
    .insert({
      anime_id: animeId,
      user_id: userId,
      status: status,
    })
    .select("*, anime(*)")
    .single();

  if (error) throw new Error(error.message);

  // Create status_update entry in feed
  await createStatusUpdateEntry(userId, animeId, status);

  return data as UserAnimeEntry;
};

/**
 * Update an existing user anime entry
 *
 * @param entryId uuid of the user anime entry
 * @param updates partial updates to apply (status, rating, or review)
 * @returns the updated UserAnimeEntry
 */
export const updateUserAnimeEntry = async (
  entryId: string,
  updates: Partial<Pick<UserAnimeEntry, "status" | "rating" | "review">>
): Promise<UserAnimeEntry> => {
  // First, fetch the current entry to compare values
  const { data: currentEntry, error: fetchError } = await supabase
    .from("user_anime_entries")
    .select("user_id, anime_id, status, rating")
    .eq("id", entryId)
    .single();
  if (fetchError) throw new Error(fetchError.message);

  // Update the entry
  const { data, error } = await supabase
    .from("user_anime_entries")
    .update(updates)
    .eq("id", entryId)
    .select("*, anime(*)")
    .single();
  if (error) throw new Error(error.message);

  // Status changes still post feed events; rating changes don't create
  // posts — the entry page displays the author's current rating live
  const changedStatus =
    updates.status && updates.status !== currentEntry.status;

  if (changedStatus) {
    await createStatusUpdateEntry(
      currentEntry.user_id,
      currentEntry.anime_id,
      updates.status!
    );
  }

  return data as UserAnimeEntry;
};

/**
 * Remove an anime from the user's list
 *
 * @param entryId uuid of the user anime entry to remove
 */
export const removeUserAnimeEntry = async (entryId: string): Promise<void> => {
  // First, get the entry details to delete associated entries
  const { data: entry, error: fetchError } = await supabase
    .from("user_anime_entries")
    .select("user_id, anime_id")
    .eq("id", entryId)
    .single();
  if (fetchError) throw new Error(fetchError.message);

  // Independent tables — run together rather than one after the other.
  const [, { error }] = await Promise.all([
    deleteAutoGeneratedEntries(entry.user_id, entry.anime_id),
    supabase.from("user_anime_entries").delete().eq("id", entryId),
  ]);

  if (error) throw new Error(error.message);
};
